#ifndef __PROGRAMS_H_
#define __PROGRAMS_H_

#define DEFAULT_LETTER_COLOR 0xFFFFFF
#define DEFAULT_BACKGROUND_COLOR 0x000000
#define DELETE 0x0E
#define TAB '\t'
#define CURSOR 127
#define SCREEN1_HEIGHT 382
#define SCREEN2_HEIGHT 382
#define LETTER_HEIGHT 16
#define LETTER_WIDTH 8
#define WIDTH 1024
#define DIM_BUFFER WIDTH/8
#define ESC 0x1B

#endif